# Generated by Django 3.1.7 on 2021-05-20 09:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=120, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_teacher', models.BooleanField(default=False, verbose_name='Преподавтель')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Учетная запись')),
            ],
            options={
                'verbose_name': 'Участник сообщества',
                'verbose_name_plural': 'Участники сообщества',
            },
        ),
        migrations.CreateModel(
            name='StudentGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=120, verbose_name='Наименование')),
                ('start_date', models.DateField(default='2021-01-01', verbose_name='Дата начала')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Группа учащегося',
                'verbose_name_plural': 'Группы учащихся',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_date', models.DateTimeField(verbose_name='Дата занятия')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.studentgroup', verbose_name='Группа')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.people', verbose_name='Преподавтель')),
            ],
            options={
                'verbose_name': 'Рассписание занятия',
                'verbose_name_plural': 'Рассписание',
            },
        ),
        migrations.CreateModel(
            name='PeopleInGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.studentgroup', verbose_name='Группа')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.people', verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Состав группы',
                'verbose_name_plural': 'Составы групп',
            },
        ),
    ]
